version: "3"

services:
  database:
    image: mysql
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=images
    ports:
      - "3306:3306"
#    volumes:
#      - /home/user/IdeaProjects/RentFinal/sql_volumes/:/var/lib/mysql
#      - /home/user/IdeaProjects/sql_volumes/:/var/lib/mysql
